volumes:
  redis-data: {}

services:
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
  bot:
    image: ghcr.io/zypperia/pipisa-bot:master
    restart: unless-stopped
